spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL用 com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lab_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai  # MySQL改为 jdbc:mysql://localhost:3306/lab_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: zbh997788  # 替换为你的数据库密码
  data:
   redis:
    host: 127.0.0.1
    port: 6379          # 默认端口，可省略
security:
  jwt:
    secret: demo-jwt-secret-key-for-spring-security-2026
    expiration-millis: 7200000